Move prover returns: exiting with bytecode transformation errors
error: function `A::mutate_at` is opaque but its specification does not have a modifies clause for `A::S`
   ┌─ tests/sources/functional/ModifiesTypeTest.move:22:5
   │
22 │ ╭     spec mutate_at {
23 │ │         pragma opaque = true;
24 │ │     }
   │ ╰─────^

error: caller `B::mutate_S_test1_incorrect` specifies modify targets for `A::S` but callee `A::mutate_at` does not
   ┌─ tests/sources/functional/ModifiesTypeTest.move:30:5
   │
30 │ ╭     public fun mutate_S_test1_incorrect(addr: address) {
31 │ │         A::mutate_at(addr);
32 │ │     }
   │ ╰─────^
