Move prover returns: exiting with boogie verification errors
error: abort not covered by any of the `aborts_if` clauses
   ┌─ tests/sources/functional/script_incorrect.move:11:1
   │
11 │ ╭ spec main {
12 │ │     pragma verify = true;
13 │ │     aborts_if false;
14 │ │ }
   │ ╰─^
   │
   ┌─ tests/sources/functional/script_provider.move:18:9
   │
18 │         assert(Signer::address_of(account) == @0x1, 1);
   │         ---------------------------------------------- abort happened here with code 0x1
   │
   =     at tests/sources/functional/script_incorrect.move:7: main
   =         account = <redacted>
   =     at tests/sources/functional/script_incorrect.move:8: main
   =     at tests/sources/functional/script_provider.move:17: register
   =         account = <redacted>
   =     at tests/sources/functional/script_provider.move:18: register
   =         <redacted> = <redacted>
   =     at tests/sources/functional/script_provider.move:18: register
   =         ABORTED
